

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from '@/components/layout/header/header'
import Footer from "@/components/layout/footer";

const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  
  return (
    <html lang="en">
      <body className={`flex flex-col ${roboto.variable}`}>
        
        <Header/>
          <main className="flex justify-center grow">
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}